### ISSUE TITLE
td.reset() does not reset all replaced modules

### ISSUE THREAD

**Issue by qswinson** [testdouble/testdouble.js#473] opened 2021-10-05 00:28 UTC
### Description
When a module is replaced on a nested module, `td.reset()` does not unset the replacement.

### Issue

I have a helper file that is required by two different services. Service A, Service B, and the helper file all require File C. I do a td.replace for File C for my unit tests for both services. However, the helper file always has the td.replace definition for the first test executed. I call td.reset in both tests but it does not reset the helper file dependencies.

### Environment

- [ ] `node -v` output: v12.22.3
- [ ] `npm -v` (or `yarn --version`) output: 6.14.13
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.16.2

### Example Repo

https://github.com/qswinson/apple-train.git

**Comment by searls** [comment] 2021-10-05 12:18
Hello! Could you please post a reproducible example repo so we can look at this?

**Comment by searls** [comment] 2021-10-05 14:46
Looking at your code, this is an apparent dupe of #379 and #293.

In #379 I [left a long comment](https://github.com/testdouble/testdouble.js/issues/379#issuecomment-415868424) on why I didn't factor this use into td.js -- when I use a mocking library, I either mock all of a subject' sdependencies or none of them to achieve full isolation, and to avoid mixing levels of abstraction.

That said, this is clearly not behaving obviously, either, and I'd welcome a patch to td.js (or more likely, its dependency [quibble](https://github.com/testdouble/quibble)) that would enable this. But as of right now, replacing transitive dependencies is not supported.

**Closed by searls** 2021-10-05 14:46 UTC
