### ISSUE TITLE
How to verify the value of "this" keyword on a call?

### ISSUE THREAD

**Issue by andreventuravale** [testdouble/testdouble.js#292] opened 2017-10-09 12:39 UTC
I want td.verify(...) to also check the value of this keyword have a specific value.

Is there anyway to accomplish this?

**Comment by searls** [comment] 2017-10-09 12:53
Agree!

This is not implemented, but is a dupe of this open issue: https://github.com/testdouble/testdouble.js/issues/207

**Closed by searls** 2017-10-09 12:53 UTC
