### ISSUE TITLE
Does not work with jest

### ISSUE THREAD

**Issue by aaronjensen** [testdouble/testdouble.js#128] opened 2016-09-01 19:49 UTC
See https://github.com/facebook/jest/issues/1537

and a repro: https://github.com/aaronjensen/jest-testdouble-repro

```
 PASS  client/test/components/forms/GridSelect.test.js
TypeError: content.match is not a function
    at module.exports.content (/Users/aaronjensen/Source/jest-testdouble-repro/node_modules/jest-util/build/separateMessageFromStack.js:22:32)
    at formatExecError (/Users/aaronjensen/Source/jest-testdouble-repro/node_modules/jest-util/build/messages.js:64:21)
    at onRunFailure (/Users/aaronjensen/Source/jest-testdouble-repro/node_modules/jest-cli/build/TestRunner.js:166:35)
    at promise.then.then.then.catch.err (/Users/aaronjensen/Source/jest-testdouble-repro/node_modules/jest-cli/build/TestRunner.js:236:18)
```

**Comment by searls** [comment] 2016-09-10 04:06
Do you have any insight into the cause of this?  I have no experience with jest so I don't really know where to begin. Someone mentioned an old version of lodash—does testdouble.js need its version updated?

**Comment by aaronjensen** [comment] 2016-09-10 04:53
That'd help w/ one of the issues. Maybe it'd help w/ this one too, I do not know. Does the repro repo work for you?

**Comment by searls** [comment] 2016-12-21 17:09
This appears to work for me.

```
$ npm run jest

> @ jest /Users/justin/code/testdouble/testdouble.js/examples/jest
> jest

 PASS  client/test/components/forms/GridSelect.enzyme.test.js
 PASS  client/test/components/forms/GridSelect.test.js
Test Summary
 › Ran all tests.
 › 2 tests passed (2 total in 2 test suites, run time 1.253s)
```

**Comment by searls** [comment] 2016-12-21 17:23
Ok, I just added your jest example to the build (I added a simple call through to `td.when` to make sure the lib actually works) in 9b7706503b6c9fa9469c9ddcb06f174498e61160

Closing this since I can't reproduce.

**Closed by searls** 2016-12-21 17:23 UTC

**Comment by twilczek** [comment] 2018-02-02 12:25
Hi @searls 

I can confirm td.replace doesn't work with jest. I created a small GIF showing the error:
[http://g.recordit.co/OzKtY9IF8F.gif](url). 
In the GIF you can see I am running the same test using Mocha and Jest. 
Unfortunately td.replace fails to replace required function when I run the spec with Jest.

I have created the repo where you can reproduce the issue:
git clone https://github.com/twilczek/jestFailRepro.git
npm install
npm run test:jest (fails)
npm run test:mocha (works)

**Comment by searls** [comment] 2018-02-28 15:12
FYI that first class Jest support is now a thing

https://github.com/testdouble/testdouble-jest

**Comment by twilczek** [comment] 2018-02-28 15:49
@searls Awesome, thanks! :)
