### ISSUE TITLE
Feature request: Partial object matchers

### ISSUE THREAD

**Issue by bjarketrux** [testdouble/testdouble.js#141] opened 2016-10-06 06:44 UTC
Currently we can do
```
var brew = td.function()
td.when(brew(td.matchers.contains({ingredient: 'beans'}))).thenReturn('coffee')
```

It would be nice to do something like this:
```
var brew = td.function()
td.when(brew(td.matchers.contains({ ingredient: td.matchers.isA(String) }))).thenReturn('coffee')
```

Or even:
```
var brew = td.function()
td.when(brew({ ingredient: td.matchers.isA(String) })).thenReturn('coffee')
```

This is especially true for complex objects or dates.
[Jasmine equivalent](http://jasmine.github.io/edge/introduction.html#section-String_Matching_with_<code>jasmine.stringMatching</code>)

**Comment by searls** [comment] 2016-10-07 11:31
I believe this is a dupe of: https://github.com/testdouble/testdouble.js/pull/109

**Closed by searls** 2016-10-07 11:31 UTC

**Comment by bjarketrux** [comment] 2016-10-07 15:12
Ah yes you are correct. Sorry
