### ISSUE TITLE
Could you make td.when() support a Strict Mode?

### ISSUE THREAD

**Issue by klondikemarlen** [testdouble/testdouble.js#442] opened 2020-04-02 20:16 UTC
### Description
When I'm stubbing an internal function, I like to check that my test is working by mutating the code under test. Using td.when() I find that the error message my code is throwing might be very confusing to the next developer debugging it.
i.e. If they change my function invocation td.when() will silently return `undefined`.

This undefined value then triggers a failure somewhere much farther down (nowhere near the function invocation under test).

### Issue

I propose adding a `strict` paramter to td.when.
e.g.
```js
def('apiCreateVersionMock', () => td.replace(api, 'createVersion'))

beforeEach(() => {
  td.when($apiCreateVersionMock($uploadId, $file, $data, $callbacks), {
    strict: true,
  }).thenResolve('some promise')
})
```

Then in my code under test, when I call the `api.createVersion` with incorrect arguments, instead of returning undefined, it would throw an exception containing a diff of the arguments sent vs. the arguments expected.

**Comment by searls** [comment] 2020-04-03 02:12
Sorry, but we won't be adding this. This has been suggested several times, but testdouble.js was designed specifically to avoid this pattern of mock usage, because it typically inhibits [Arrange, Act, Assert](https://github.com/testdouble/contributing-tests/wiki/Arrange-Act-Assert) by putting an (effective) assertion in the Arrange phase of the test, and because tools & teams that use enforced stubs (mocks) tend to overuse them such that their tests go beyond what is [necessary](https://blog.testdouble.com/posts/2020-02-25-necessary-and-sufficient/) resulting in overspecified tests.

**Closed by searls** 2020-04-03 02:12 UTC

**Comment by klondikemarlen** [comment] 2020-04-03 14:51
Fair enough! I'll read those articles :)
