### ISSUE TITLE
Consider ignoreExtraArgs method instead of parameter

### ISSUE THREAD

**Issue by focusaurus** [testdouble/testdouble.js#143] opened 2016-10-12 15:12 UTC
I'd like to suggest making `ignoreExtraArgs` handled via a method call syntax instead of a function parameter to `td.when()`.

So instead of:

```js
td.replace(db, 'query')
td.when(db.query('users', 'name'), {ignoreExtraArgs: true})
  .thenResolve([])
```

I'd propose:

```js
td.replace(db, 'query')
td.when(db.query('users', 'name'))
  .ignoreExtraArgs()
  .thenResolve([])
```

My motivation is that after using testdouble heavily with a 5-developer team over 6 months, we've wasted a lot of time being confused and tracking down test failures when one of us makes the following very easy mistake:

```js
// What they intend/should code:
td.when(db.query('users', 'name'), {ignoreExtraArgs: true})
  .thenResolve([])

// What they accidentally code
td.when(db.query('users', 'name', {ignoreExtraArgs: true}))
  .thenResolve([])
```

One misplaced close parentheses sends them down a long debugging rabbit hole of confusion. This has happened several times to several developers, usually when refactoring existing code/tests. We know to watch for it now, but it was a hard-learned lesson.

The tests typically end up throwing an exception `TypeError: Cannot read property 'then' of undefined`, which in a promise-heavy codebase is tantamount to "something didn't return a promise when it should have", but that implicates almost every function in the project.

I believe the explicit method syntax will reduce mistakes here, especially when formatted as above with each chained dot operator starting a new line.

I have only briefly looked at the source of `src/when.coffee` and I believe this changed API to be technically possible, but I could be wrong about that.

**Comment by searls** [comment] 2016-10-14 16:55
Thanks for your proposal and for providing an (entirely valid and understandable!) rationale, however I'm not willing to move `td.when` and `td.verify` to a chaining API. A few reasons:

1. `td.when` currently returns the test double, which itself is necessary for one-lineable instantiation. (example: `td.when(td.function()('pants')).thenReturn('yup')` return the double that returns `'yup'`. Moving to a chaining API would prevent this because we'd instead have to return some chainable-object (oddly enough, it was [exactly this problem](https://github.com/sinonjs/sinon/issues/817) I raised on Sinon that led me to write testdouble.js).

2. You could (and should) point out at this point that chained _configuration_ methods don't resolve the chain so those are okay, and that `thenReturn` and so on can safely do so. You'd be right, but that's a lot of nuance for users to keep in their head. When people see a chaining/fluent API they generally assume it's safe to call whatever they like in whatever order they like, and we'd have to educate them about _why this config is different_ (and I'm not sure it is).

3. If you read the aforementioned sinon [issue](https://github.com/sinonjs/sinon/issues/817) you'll see mention of lots of issues being opened because of the move to a chainable API. these things are really hard to test and manage, and are much trickier to implement (and harder to understand) than a single-depth configuration object

4. It's my opinion that the vast majority of `when` and `verify` calls should not require matchers nor custom configuration options. If you're finding that most or all of your stubbings are also passing `ignoreExtraArgs`, then it's my opinion that those tests are incomplete because they're not verifying the args are what you expect, and so I wouldn't want to change the library to encourage frequent use of those options. They exist because there are cases when they're genuinely necessary, but every time you reach for any of them it should feel a little painful as if to remind you that _always_ leaning on them is an anti-pattern.

If you disagree with the above or see things differently, I'd rather dig into the root cause issue of why you're always setting `ignoreExtraArgs`, rather than guard against typos when setting it so often (which seems to me like treating the symptom). Moreover, if we just see things differently, I'd recommend you write a test helper that encapsulates this pattern for yourself so that you're not calling `td.when` directly but instead setting things up how you always do and without the risk for error or the needless verbosity from repeating yourself.

**Closed by searls** 2016-10-14 16:55 UTC

**Comment by focusaurus** [comment] 2016-10-14 21:28
OK, understood and thank you for the detailed response. I suspected there might be technical reasons such an API would not work, and also that you were unlikely to agree with this proposal.

I actually tried to encapsulate all this into a test helper but after about 4 hours of it confusingly not working I abandoned it.

Just for your log of how users are using/misusing the library, we are mocking database query calls. Also note we are not **always** using `ignoreExtraArgs`, but we are using it with some frequency. The database driver we mock takes a final `options` argument that is always a side implementation detail not affecting the behavior of our code, so that's one case where we use `ignoreExtraArgs`. Also we often just need to mock the DB working for a bunch of `INSERT` statements that need to return a promise for control flow only, there's no meaningful value returned, so we use that situation to affect a "simulate all INSERTS into the DB working" mode and handle our examination of the specifics later.

One of the reasons we use matchers is the args to the DB are SQL strings and we don't want to do exact matching on those such that changing the whitespace formatting breaks the tests, but we also don't want to spend a month building a matcher that parses them into an AST and does a logical equivalence comparison.

**Comment by searls** [comment] 2016-10-17 20:03
I won't be able to provide very much advice at such a distance (you know your codebase much better than I ever will), so I can't comment much on what you're describing. All I'll say is that the pattern you're describing sounds like the API you're faking requires the caller to know a ton of detail about its implementation.

In broad strokes, if I have a fake like:

```
td.when(repository.insert('BLAH (?,?,?,?)…………… INTO (foo, bar, biz, baz)', [obj.blah, obj.boop, obj.beep, obj.blip]).thenResolve([thing1, thing2])
```

That would indeed be a painful thing to stub, but a more productive response to that pain would be to introduce an easier-to-call API that sat between my subject, the caller, and the implementation details of that call to `repository`. That way the stub would really just be:

```js
td.when(thingSaver.save(obj)).thenResolve([thing1, thing2])
```

And effectively put that query complexity into the thing responsible just for mapping my domain objects into structured queries.

In general, when something is hard to stub or verify, it's a sort of feedback like this that my dependency is hard to use and should be redesigned. Almost without exception, if a dependency is easy to use, it'll be easy to stub, too.
