### ISSUE TITLE
td.explain does not work on new instance of td.replace('lib') 

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [testdouble/testdouble.js#323] opened 2018-01-17 09:40 UTC
## Info:
It appears that `td.explain` does not seem to work on new instances (context) of replaced libraries.

## Current behaviour:
```js
let td = require('testdouble')
let someLibrary = td.replace('bull') ///Whichever library you want. I Had bull installed, so I tested with that
let instance = new someLibrary()
console.log('instance', instance, td.explain(instance), typeof(instance))
console.log(td.explain(someLibrary))
```

Running this results in;

```
$ node weirdness.js
instance testDouble {} { name: undefined,
  callCount: 0,
  calls: [],
  description: 'This is not a test double.',
  isTestDouble: false } object
{ name: 'bull: Queue',
  callCount: 1,
  calls: [ { args: [], context: testDouble {} } ],
  description: 'This test double `bull: Queue` has 0 stubbings and 1 invocations.\n\nInvocations:\n  - called with `()`.',
  isTestDouble: true }
```

## Expected behaviour:

I expected something like the following:
```
$ node weirdness.js
instance testDouble {} { name: `bull: Queue context`,
  callCount: 0,
  calls: [],
  description: 'This test double `bull: Queue context` has 0 stubbings and 0 invocations.',
  isTestDouble: true } object
{ name: 'bull: Queue',
  callCount: 1,
  calls: [ { args: [], context: testDouble {} } ],
  description: 'This test double `bull: Queue` has 0 stubbings and 1 invocations.\n\nInvocations:\n  - called with `()`.',
  isTestDouble: true }
```

--- 
testdouble@3.3.2

**Comment by searls** [comment] 2018-01-17 12:39
td.explain currently only supports being passed functions themselves, not objects that reference functions.

**Comment by searls** [comment] 2018-01-17 16:56
Duplicate of #48

**Closed by searls** 2018-01-17 16:56 UTC
