### ISSUE TITLE
allow to disable the stubbing and verifying warning

### ISSUE THREAD

**Issue by luxferresum** [testdouble/testdouble.js#453] opened 2020-09-07 09:14 UTC
testdouble prints [a warning when stubbing and verifying the same interaction](https://github.com/testdouble/testdouble.js/blob/master/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double). However there are a few valid use-cases so it should be possible to overwrite this warning.

A valid use case is code that has a side effect but no return value and relies on the result of a mock.

Lets say I want to test this function:

```
async function save(message, etag) {
  const res = await fetch('http://example.com', {
    headers: { 'if-match': etag },
    body: JSON.stringify({ message }),
  });
  if(res.status < 200 || res.status >= 300) {
    throw 'error while saving a message';
  }
}
```

then I need to ensure that the stubbed `fetch` does return `status:200`. However if I only stub then a no-op would pass the test. So I need to verify to ensure that the test actually does anything.

So is there any way to disable the warning?

**Comment by searls** [comment] 2020-09-10 14:09
You can configure warnings globally with `td.config` ([doc](https://github.com/testdouble/testdouble.js/blob/master/docs/C-configuration.md#tdconfig))

This is a dupe of several similar issues ( #250, #245, #199, #148, #389) and would be fixed by implementing #390

**Closed by searls** 2020-09-10 14:09 UTC
