### ISSUE TITLE
Improve td.replace error message for incorrect module path

### ISSUE THREAD

**Issue by myoffe** [testdouble/testdouble.js#355] opened 2018-03-20 17:11 UTC
Calling `td.replace` with an incorrect module path prints out the following error:

```
 TypeError: Cannot read property 'join' of undefined
      at requireAt (node_modules/testdouble/lib/replace/module.js:34:32)
      at default_1 (node_modules/testdouble/lib/replace/module.js:15:21)
      at default_1 (node_modules/testdouble/lib/replace/index.js:10:33)
      at Context.beforeEach (app/users/reset-password.test.js:22:12)
```

It should print something more informative, like the error message from `require`:

`Error: Cannot find module '/incorrect/path/to/module'`

### Environment
`node v8.10.0`
`testdouble@3.5.2`

**Comment by searls** [comment] 2018-03-20 19:01
Absolutely agree. Can you give a specific example of what the correct name was and what was wrong? I ask because there are several different failure paths for module replacement and I want to be clear I understand your case

**Comment by myoffe** [comment] 2018-03-20 21:09
In my case the failure was caused by `replace('./hash')`, while the correct path was `'../auth/hash'`.
This was inside the test file `<project root>/app/users/reset-password.test.js`

**Comment by searls** [comment] 2018-03-25 12:31
This is sort of a dupe of #261 except the message apparently got worse at some point.

**Closed** 2018-04-29 15:57 UTC
Labels: enhancement

**Comment by searls** [comment] 2018-04-29 16:01
Landed in 3.8.0
